[batter_percent]
Description="Battery percent in range 0 -> 100"
Command="acpi -b | grep -o '[0-9]*%' | grep -o '[0-9]*'"

[energy_now]
Description="Example of reading a file"
File="/sys/class/power_supply/BAT0/energy_now"

[counter]
Description="Example for counter"
Labels=["A"]
#MetricType="counter"
File="example.output"

[dropbox]
Description="Free space on dropbox (units are bytes)"
Labels=["type"]
Command="""rclone about --json Dropbox: | jq -r 'to_entries | map(["type=\\""+.key+"\\"", .value]) | .[] | @tsv'"""